project_id = "aryusbuyyoxkeigzsnko"

[functions.card2crypto]
verify_jwt = false

[functions.twilio-verify]
verify_jwt = false

[functions.coinbase-headless]
verify_jwt = false

[functions.coinbase-config]
verify_jwt = false

[functions.moonpay-sign]
verify_jwt = false

[functions.stripe-onramp]
verify_jwt = false

[functions.stripe-config]
verify_jwt = false

[functions.wallet-auth]
verify_jwt = false
